# Format variables:
# %sender% - ник отправителя
# %message% - сообщение
# %result% - результат (try, dice, coin)

commands:
  me:
    enabled: true
    format: '§7* %sender% §o%message% *'
    usage: '[§c!§f] §cИспользуй: /me <сообщение>'
    radius: 20
  gdo:
    enabled: true
    format: '§c*§f %sender% %action% §e'
    usage: '[§c!§f] §cИспользуй: /gdo <сообщение>'
  gtry:
    enabled: true
    format: '§c*§f %sender%: %action% (%result%§f)'
    usage: '[§c!§f] §cИспользуй: /gtry <сообщение>'
    results:
      - '§aУспешно'
      - '§cНеуспешно'
  gme:
    enabled: true
    format: '§7* %sender% §o%message% *'
    usage: '[§c!§f] §cИспользуй: /gme <сообщение>'
  try:
    enabled: true
    format: '§e*§f %sender%: %action% (%result%§f)'
    usage: '[§c!§f] §cИспользуй: /try <действие>'
    radius: 20
    results:
      - '§aУспешно'
      - '§cНеуспешно'
  do:
    enabled: true
    format: '§6*§f %sender% %action% §e'
    usage: '[§c!§f] §cИспользуй: /do <действие>'
    radius: 20
  coin:
    enabled: true
    format: '§8*§6 %sender% §fподбросил монетку (§6%result%§f) §8'
    radius: 20
    obverse: '§6Орел'
    reverse: '§6Решка'
  gcoin:
    enabled: true
    format: '§8*§6 %sender% §fподбросил монетку (§6%result%§f) §8'
    obverse: '§6Орел'
    reverse: '§6Решка'
  whisper:
    enabled: true
    format: '§7§o%sender% шепчет: %message%'
    usage: '[§c!§f] §cИспользуй: /whisper <сообщение>'
    radius: 4
  dice:
    enabled: true
    format: '§8*§6 %sender% §fвыбросил §6%result%§f на кубике §8'
    radius: 20
    max_value: 17
    min_value: 6
  gdice:
    enabled: true
    format: '§c*§6 %sender% §fвыбросил §6%result%§f на кубике §8'
    max_value: 24
    min_value: 1